// Created from bdf2c Version 3, (c) 2009, 2010 by Lutz Sammer
//	License AGPLv3: GNU Affero General Public License version 3

#include "font.h"

	/// character bitmap for each encoding
static const unsigned char __font_bitmap__[] = {
//   0 $00 'C000'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   1 $01 'diamond'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   2 $02 'checkerboard'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   3 $03 'HT'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   4 $04 'FF'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   5 $05 'CR'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   6 $06 'LF'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   7 $07 'degree'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   8 $08 'plusminus'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//   9 $09 'NL'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  10 $0a 'VT'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  11 $0b 'cornerbottomright'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  12 $0c 'cornertopright'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  13 $0d 'cornertopleft'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  14 $0e 'cornerbottomleft'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  15 $0f 'junctioncenter'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  16 $10 'horizhigh'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  17 $11 'horizmedhigh'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  18 $12 'horizmed'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  19 $13 'horizmedlow'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  20 $14 'horizlow'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  21 $15 'edgeleft'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  22 $16 'edgeright'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  23 $17 'edgebottom'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  24 $18 'edgetop'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  25 $19 'vert'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  26 $1a 'lessequal'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  27 $1b 'greaterequal'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  28 $1c 'pi'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  29 $1d 'notequal'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  30 $1e 'poundsterling'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  31 $1f 'dotmath'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  32 $20 'space'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  33 $21 '!'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  34 $22 '"'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  35 $23 '#'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  36 $24 '$'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  37 $25 '%'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  38 $26 '&'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  39 $27 '''
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  40 $28 '('
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  41 $29 ')'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  42 $2a '*'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  43 $2b '+'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  44 $2c ','
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  45 $2d '-'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  46 $2e '.'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  47 $2f '/'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  48 $30 '0'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  49 $31 '1'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  50 $32 '2'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  51 $33 '3'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  52 $34 '4'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  53 $35 '5'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  54 $36 '6'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  55 $37 '7'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  56 $38 '8'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  57 $39 '9'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  58 $3a ':'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  59 $3b ';'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  60 $3c '<'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  61 $3d '='
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  62 $3e '>'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  63 $3f '?'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  64 $40 '@'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  65 $41 'A'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  66 $42 'B'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  67 $43 'C'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  68 $44 'D'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  69 $45 'E'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  70 $46 'F'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  71 $47 'G'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  72 $48 'H'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  73 $49 'I'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  74 $4a 'J'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  75 $4b 'K'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  76 $4c 'L'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  77 $4d 'M'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  78 $4e 'N'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  79 $4f 'O'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  80 $50 'P'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  81 $51 'Q'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  82 $52 'R'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  83 $53 'S'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  84 $54 'T'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  85 $55 'U'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  86 $56 'V'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  87 $57 'W'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  88 $58 'X'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  89 $59 'Y'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  90 $5a 'Z'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  91 $5b '['
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  92 $5c '\'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  93 $5d ']'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  94 $5e '^'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  95 $5f '_'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  96 $60 '`'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  97 $61 'a'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  98 $62 'b'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
//  99 $63 'c'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 100 $64 'd'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 101 $65 'e'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 102 $66 'f'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 103 $67 'g'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 104 $68 'h'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 105 $69 'i'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 106 $6a 'j'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 107 $6b 'k'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 108 $6c 'l'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 109 $6d 'm'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 110 $6e 'n'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 111 $6f 'o'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 112 $70 'p'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 113 $71 'q'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 114 $72 'r'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 115 $73 's'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 116 $74 't'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 117 $75 'u'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 118 $76 'v'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 119 $77 'w'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 120 $78 'x'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 121 $79 'y'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 122 $7a 'z'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 123 $7b '{'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 124 $7c '|'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 125 $7d '}'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 126 $7e '~'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 127 $7f 'C177'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 160 $a0 'nobreakspace'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 161 $a1 'exclamdown'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 162 $a2 'cent'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 163 $a3 'sterling'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 164 $a4 'currency'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 165 $a5 'yen'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 166 $a6 'brokenbar'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 167 $a7 'section'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 168 $a8 'diaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 169 $a9 'copyright'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 170 $aa 'ordfeminine'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 171 $ab 'guillemotleft'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 172 $ac 'notsign'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 173 $ad 'hyphen'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 174 $ae 'registered'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 175 $af 'macron'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 176 $b0 'degree'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 177 $b1 'plusminus'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 178 $b2 'twosuperior'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 179 $b3 'threesuperior'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 180 $b4 'acute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 181 $b5 'mu'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 182 $b6 'paragraph'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 183 $b7 'periodcentered'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 184 $b8 'cedilla'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 185 $b9 'onesuprerior'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 186 $ba 'masculine'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 187 $bb 'guillemotright'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 188 $bc 'onequarter'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 189 $bd 'onehalf'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 190 $be 'threequarters'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 191 $bf 'questiondown'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 192 $c0 'Agrave'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 193 $c1 'Aacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 194 $c2 'Acircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 195 $c3 'Atilde'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 196 $c4 'Adiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 197 $c5 'Aring'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 198 $c6 'AE'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 199 $c7 'Ccedilla'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 200 $c8 'Egrave'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 201 $c9 'Eacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 202 $ca 'Ecircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 203 $cb 'Ediaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 204 $cc 'Igrave'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 205 $cd 'Iacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 206 $ce 'Icircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 207 $cf 'Idiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 208 $d0 'ETH'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 209 $d1 'Ntilde'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 210 $d2 'Ograve'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 211 $d3 'Oacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 212 $d4 'Ocircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 213 $d5 'Otilde'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 214 $d6 'Odiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 215 $d7 'multiply'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 216 $d8 'Ooblique'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 217 $d9 'Ugrave'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 218 $da 'Uacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 219 $db 'Ucircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 220 $dc 'Udiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 221 $dd 'Yacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 222 $de 'THORN'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 223 $df 'ssharp'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 224 $e0 'agrave'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 225 $e1 'aacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 226 $e2 'acircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 227 $e3 'atilde'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 228 $e4 'adiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 229 $e5 'aring'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 230 $e6 'ae'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 231 $e7 'ccedilla'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 232 $e8 'egrave'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 233 $e9 'eacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 234 $ea 'ecircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 235 $eb 'ediaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 236 $ec 'igrave'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 237 $ed 'iacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 238 $ee 'icircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 239 $ef 'idiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 240 $f0 'eth'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 241 $f1 'ntilde'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 242 $f2 'ograve'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 243 $f3 'oacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 244 $f4 'ocircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 245 $f5 'otilde'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 246 $f6 'odiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 247 $f7 'division'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 248 $f8 'oslash'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 249 $f9 'ugrave'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 250 $fa 'uacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 251 $fb 'ucircumflex'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 252 $fc 'udiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 253 $fd 'yacute'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 254 $fe 'thorn'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
// 255 $ff 'ydiaeresis'
//	width 9, bbx 0, bby -3, bbw 9, bbh 15
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
	XXXX__X_,XXXX_X__,
};

	/// character width for each encoding
static const unsigned char __font_widths__[] = {
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
	9,
};

	/// character encoding for each index entry
static const unsigned short __font_index__[] = {
	0,
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	8,
	9,
	10,
	11,
	12,
	13,
	14,
	15,
	16,
	17,
	18,
	19,
	20,
	21,
	22,
	23,
	24,
	25,
	26,
	27,
	28,
	29,
	30,
	31,
	32,
	33,
	34,
	35,
	36,
	37,
	38,
	39,
	40,
	41,
	42,
	43,
	44,
	45,
	46,
	47,
	48,
	49,
	50,
	51,
	52,
	53,
	54,
	55,
	56,
	57,
	58,
	59,
	60,
	61,
	62,
	63,
	64,
	65,
	66,
	67,
	68,
	69,
	70,
	71,
	72,
	73,
	74,
	75,
	76,
	77,
	78,
	79,
	80,
	81,
	82,
	83,
	84,
	85,
	86,
	87,
	88,
	89,
	90,
	91,
	92,
	93,
	94,
	95,
	96,
	97,
	98,
	99,
	100,
	101,
	102,
	103,
	104,
	105,
	106,
	107,
	108,
	109,
	110,
	111,
	112,
	113,
	114,
	115,
	116,
	117,
	118,
	119,
	120,
	121,
	122,
	123,
	124,
	125,
	126,
	127,
	160,
	161,
	162,
	163,
	164,
	165,
	166,
	167,
	168,
	169,
	170,
	171,
	172,
	173,
	174,
	175,
	176,
	177,
	178,
	179,
	180,
	181,
	182,
	183,
	184,
	185,
	186,
	187,
	188,
	189,
	190,
	191,
	192,
	193,
	194,
	195,
	196,
	197,
	198,
	199,
	200,
	201,
	202,
	203,
	204,
	205,
	206,
	207,
	208,
	209,
	210,
	211,
	212,
	213,
	214,
	215,
	216,
	217,
	218,
	219,
	220,
	221,
	222,
	223,
	224,
	225,
	226,
	227,
	228,
	229,
	230,
	231,
	232,
	233,
	234,
	235,
	236,
	237,
	238,
	239,
	240,
	241,
	242,
	243,
	244,
	245,
	246,
	247,
	248,
	249,
	250,
	251,
	252,
	253,
	254,
	255,
};

	/// bitmap font structure
const struct bitmap_font font = {
	.Width = 9, .Height = 15,
	.Chars = 224,
	.Widths = __font_widths__,
	.Index = __font_index__,
	.Bitmap = __font_bitmap__,
};

